spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbconnection
    username: litu
    password: litu12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: DEBUG
    web: DEBUG
server:
  port: 8081